name: Update README Stats

on:
  schedule:
    - cron: '20 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Stats
        uses: thanhhaudev/github-stats@v1.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_METRICS: "CODING_STREAK,COMMIT_TIMES_OF_DAY,COMMIT_DAYS_OF_WEEK,LANGUAGE_PER_REPO,LANGUAGES_AND_TOOLS"
          SHOW_LAST_UPDATE: "true"
          TIME_ZONE: "Europe/Berlin"
          TIME_LAYOUT: "Mon, 02 Jan 2006 15:04:05 MST"
          PROGRESS_BAR_VERSION: "1"
          HIDE_REPO_INFO: "true"
          SECTION_NAME: "fun-facts"
          COMMIT_MESSAGE: "❤️ update fun facts"
